export const testIds = Object.freeze({
  ticketCard: 'ticket-card',
  labelDot: 'label-dot',
  labelOverflowChip: 'label-overflow-chip',
  epicChip: 'epic-chip',
  syncIndicator: 'sync-indicator',
  refreshButton: 'refresh-button',
  onlyWorkspaceToggle: 'only-workspace-toggle',
  subIssueRow: 'sub-issue-row',
  linkedIssueRow: 'linked-issue-row',
  mrSection: 'mr-section',
  reviewerAvatar: 'reviewer-avatar',
  ciIndicator: 'ci-indicator',
  unresolvedThreadChip: 'unresolved-thread-chip',
  mrWarningRow: 'mr-warning-row',
  mrPriorityBadge: 'mr-priority-badge',
  workspaceBadge: 'workspace-badge',
  noteBadge: 'note-badge',
  watchlistButton: 'watchlist-button',
  watchlistModal: 'watchlist-modal',
  watchlistSearchInput: 'watchlist-search-input',
  watchlistResultRow: 'watchlist-result-row',
  watchlistSection: 'watchlist-section',
  watchlistBadge: 'watchlist-badge',
  watchlistRemove: 'watchlist-remove',
  tagManagerButton: 'tag-manager-button',
  tagManagerModal: 'tag-manager-modal',
  tagNameInput: 'tag-name-input',
  tagCreateButton: 'tag-create-button',
  tagColorPicker: 'tag-color-picker',
  tagColorSwatch: 'tag-color-swatch',
  tagManagerRow: 'tag-manager-row',
  tagDeleteButton: 'tag-delete-button',
  cardTagRow: 'card-tag-row',
  cardTagChip: 'card-tag-chip',
  cardTagOverflowChip: 'card-tag-overflow-chip',
  tagControls: 'tag-controls',
  tagControlChip: 'tag-control-chip',
  tagAttachToggle: 'tag-attach-toggle',
  tagAttachOption: 'tag-attach-option',
  notesToggle: 'notes-toggle',
  notesPanel: 'notes-panel',
  notesEditor: 'notes-editor',
  notesModeWrite: 'notes-mode-write',
  notesModeRead: 'notes-mode-read',
  notesPreview: 'notes-preview',
  notesSaveState: 'notes-save-state',
  notesRefineModal: 'notes-refine-modal',
  notesRefineInput: 'notes-refine-input',
  notesRefineSubmit: 'notes-refine-submit',
  notesRefineContinue: 'notes-refine-continue',
  notesChangelog: 'notes-changelog',
  notesAiMenu: 'notes-ai-menu',
  notesAiMenuRefine: 'notes-ai-menu-refine',
  notesAiMenuAsk: 'notes-ai-menu-ask',
  notesAskModal: 'notes-ask-modal',
  notesAskInput: 'notes-ask-input',
  notesAskSubmit: 'notes-ask-submit',
  notesAskContinue: 'notes-ask-continue',
  notesAskAnswer: 'notes-ask-answer',
  notesAskCopy: 'notes-ask-copy',
  notesAskRefineToNote: 'notes-ask-refine-to-note',
  notesAskAgain: 'notes-ask-again',
  refineQuestion: 'refine-question',
  refineOption: 'refine-option',
  refineOptionRecommended: 'refine-option-recommended',
  refineFreetext: 'refine-freetext',
  bulkRefineButton: 'bulk-refine-button',
  bulkRefineModal: 'bulk-refine-modal',
  bulkRefineInput: 'bulk-refine-input',
  bulkRefineRouteButton: 'bulk-refine-route-button',
  bulkRefineMatchRow: 'bulk-refine-match-row',
  bulkRefineMatchToggle: 'bulk-refine-match-toggle',
  bulkRefineApplyButton: 'bulk-refine-apply-button',
  bulkRefineProgressRow: 'bulk-refine-progress-row',
  bulkRefineGathering: 'bulk-refine-gathering',
  bulkRefineQuestions: 'bulk-refine-questions',
  bulkRefineQuestionsApply: 'bulk-refine-questions-apply',
  collapseColumnButton: 'collapse-column-button',
  collapsedColumn: 'collapsed-column',
  navRail: 'nav-rail',
  navBoard: 'nav-board',
  navWatchlist: 'nav-watchlist',
  watchlistBoard: 'watchlist-board',
  watchlistLane: 'watchlist-lane',
  watchlistLaneCollapse: 'watchlist-lane-collapse',
  watchlistLaneCollapsed: 'watchlist-lane-collapsed',
  laneConfigButton: 'lane-config-button',
  laneConfigModal: 'lane-config-modal',
  laneConfigLaneRow: 'lane-config-lane-row',
  laneConfigAddLane: 'lane-config-add-lane',
  laneConfigDeleteLane: 'lane-config-delete-lane',
  laneConfigTagToggle: 'lane-config-tag-toggle',
  laneConfigMoveUp: 'lane-config-move-up',
  laneConfigMoveDown: 'lane-config-move-down',
  commandPalette: 'command-palette',
  commandPaletteInput: 'command-palette-input',
  commandPaletteRow: 'command-palette-row',
  commandPaletteSection: 'command-palette-section',
  commandPaletteEmpty: 'command-palette-empty',
  commandPaletteFooter: 'command-palette-footer',
  commandPaletteAction: 'command-palette-action',
  commandPaletteItemHeader: 'command-palette-item-header',
  commandPaletteSubItem: 'command-palette-sub-item',
  commandPaletteSubLoading: 'command-palette-sub-loading',
  commandPaletteSubFailed: 'command-palette-sub-failed',
  commandPaletteSubEmpty: 'command-palette-sub-empty',
  boardFilterChip: 'board-filter-chip',
  boardFilterClear: 'board-filter-clear',
} as const)

/** `data-card-kind` discriminator on `ticketCard`. */
export const cardKind = Object.freeze({
  jira: 'jira',
  reviewReal: 'review-real',
  reviewFake: 'review-fake',
  watchlist: 'watchlist',
} as const)
export type CardKind = (typeof cardKind)[keyof typeof cardKind]

/** `data-kind` discriminator on `mrWarningRow`. */
export const mrWarningKind = Object.freeze({
  noMr: 'no-mr',
  draft: 'draft',
  noReviewers: 'no-reviewers',
  mergedDesync: 'merged-desync',
  doneStillOpen: 'done-still-open',
} as const)
export type MrWarningKind = (typeof mrWarningKind)[keyof typeof mrWarningKind]

/**
 * Values of the `data-animation` attribute on `ticket-card`. State markers
 * (not interaction targets); tests select via `[data-animation="..."]`.
 */
export const cardAnimationState = Object.freeze({
  changePulse: 'changed',
  entering: 'entering',
  leaving: 'leaving',
} as const)
