export { TicketCard } from './view/TicketCard'
export { TypeIcon } from './view/TypeIcon'
export { buildCardView } from './view-model/build-card-view'
export { colorForLabel } from './domain/hash-color'
export { hasFixasapLabel } from './domain/fixasap'
export { TYPE_STYLES, type TypeStyle } from './domain/type-styles'
