// Stage 1 of bulk-refine: route one meeting transcript to the board tickets it
// discusses. A headless Claude agent is handed the transcript plus the list of
// tracked tickets ({ key, summary }) and returns, for each ticket actually
// discussed, a distilled `brief` — the per-ticket slice of the meeting, written
// as the REFINE input that stage 2 folds into that one ticket's note.
//
// Same containment as note Refine: run `--restricted` (no tools), everything in
// as text on stdin, reply parsed here. The agent can only route text it was
// given; it never reaches Jira, disk, or the notes. Pure and injectable via
// `RunClaude` so tests drive it with a fake.

import { type ClaudeRunResult, type RunClaude } from './claude-cli'

// One tracked ticket offered to the router. `summary`, `epic`, and `labels` are
// the signal the agent matches a topic against ("the login timeout thing", "user
// groups on the front end") when the transcript never names the key — which is
// the common case. The epic name in particular is often the connective tissue
// between a meeting's vocabulary and a terse ticket summary.
export type RouteTicket = {
  readonly key: string
  readonly summary: string
  readonly epic: string | null
  readonly labels: readonly string[]
}

export type RouteInput = {
  readonly transcript: string
  readonly tickets: readonly RouteTicket[]
}

// One matched ticket: its key plus the distilled brief for stage 2's refine.
export type RouteMatch = {
  readonly key: string
  readonly brief: string
}

export type RouteParse =
  | { readonly ok: true; readonly matches: readonly RouteMatch[] }
  | { readonly ok: false; readonly error: { readonly message: string } }

// The model alias resolved by the local CLI to the latest Opus.
export const ROUTE_MODEL = 'opus'

// Print mode, machine-readable envelope, no tools. Mirrors `refineClaudeArgs`;
// the routing skill body rides in as an appended system prompt.
export function routeClaudeArgs(skillBody: string): string[] {
  return [
    '-p',
    '--append-system-prompt',
    skillBody,
    '--model',
    ROUTE_MODEL,
    '--output-format',
    'json',
    '--restricted',
  ]
}

// The stdin prompt: the valid tickets as a `KEY — summary` list (each annotated
// with its epic and labels, which give the agent more to match a topic against),
// then the transcript, then the task. The skill (system prompt) carries the
// philosophy and the output contract, so this stays data + a one-line instruction.
export function buildRoutePrompt(input: RouteInput): string {
  const tickets = input.tickets.length === 0 ? '(none)' : input.tickets.map(ticketLine).join('\n')
  const transcript = input.transcript.trim() === '' ? '(none)' : input.transcript.trim()
  return [
    'Route the meeting transcript to the tracked tickets it discusses, following your instructions.',
    '',
    '## TICKETS (only these keys are valid targets)',
    tickets,
    '',
    '## TRANSCRIPT (the meeting to route)',
    transcript,
    '',
    'Return only the ticket blocks described in your instructions.',
  ].join('\n')
}

// The marker line that opens each ticket block in the agent's reply:
// `@@TICKET <KEY>` on its own line. Everything until the next marker (or the end)
// is that ticket's brief.
const TICKET_MARKER = /^[ \t]*@@TICKET[ \t]+(\S+)[ \t]*$/u

// `- KEY — summary  ·  epic: <epic>  ·  labels: a, b`, dropping the epic/labels
// segments when the ticket has none.
function ticketLine(t: RouteTicket): string {
  const parts = [`- ${t.key} — ${t.summary}`]
  if (t.epic !== null && t.epic.trim() !== '') parts.push(`epic: ${t.epic.trim()}`)
  if (t.labels.length > 0) parts.push(`labels: ${t.labels.join(', ')}`)
  return parts.join('  ·  ')
}

// Parse the CLI's `--output-format json` envelope, then the agent's own reply.
//
// The envelope is machine-generated by the CLI, so JSON is safe there. The agent
// reply is NOT parsed as JSON: briefs are multi-line markdown, and a model hand-
// writing JSON around free text reliably breaks it (raw newlines, unescaped
// quotes). Instead the agent emits delimited blocks — `@@TICKET <KEY>` then the
// brief — which no amount of markdown inside a brief can malform.
//
// Matches are filtered to the keys we actually offered and to non-empty briefs,
// and de-duplicated by key. The offered keys arrive as a normalized→canonical
// map so a case/whitespace slip in the reply (e.g. `hdr-1` for `HDR-1`) still
// lands. Every failure path becomes a tagged `{ ok: false }`, never a throw.
export function parseRouteResult(
  run: ClaudeRunResult,
  canonicalByNormalizedKey: ReadonlyMap<string, string>,
): RouteParse {
  if (run.error !== undefined) {
    return fail(`could not run the routing agent: ${run.error.message}`)
  }
  if (run.status !== 0) {
    const detail = run.stderr.trim() || run.stdout.trim() || `exit code ${run.status ?? 'unknown'}`
    return fail(`routing agent exited with an error: ${detail}`)
  }

  let envelope: { is_error?: boolean; result?: unknown }
  try {
    envelope = JSON.parse(run.stdout) as typeof envelope
  } catch {
    return fail('routing agent returned output that was not valid JSON')
  }
  if (envelope.is_error === true || typeof envelope.result !== 'string') {
    return fail('routing agent reported an error instead of a result')
  }

  return { ok: true, matches: extractBlocks(envelope.result, canonicalByNormalizedKey) }
}

// Scan the delimited reply into matches. Any preamble before the first marker is
// ignored; a brief is every line after its marker up to the next marker or the
// end. Unknown keys, blank briefs, and duplicate keys are dropped.
function extractBlocks(
  reply: string,
  canonicalByNormalizedKey: ReadonlyMap<string, string>,
): RouteMatch[] {
  const seen = new Set<string>()
  const matches: RouteMatch[] = []
  let current: { canonical: string; lines: string[] } | null = null

  const flush = () => {
    if (current === null) return
    const brief = current.lines.join('\n').trim()
    if (brief !== '' && !seen.has(current.canonical)) {
      seen.add(current.canonical)
      matches.push({ key: current.canonical, brief })
    }
    current = null
  }

  for (const line of reply.split(/\r?\n/u)) {
    const marker = line.match(TICKET_MARKER)
    if (marker) {
      flush()
      const canonical = canonicalByNormalizedKey.get(normalizeKey(marker[1] ?? ''))
      current = canonical === undefined ? null : { canonical, lines: [] }
    } else if (current !== null) {
      current.lines.push(line)
    }
  }
  flush()
  return matches
}

function normalizeKey(key: string): string {
  return key.trim().toUpperCase()
}

// Build the offered-keys map the parser filters against.
export function canonicalKeyMap(tickets: readonly RouteTicket[]): Map<string, string> {
  return new Map(tickets.map((t) => [normalizeKey(t.key), t.key]))
}

function fail(message: string): RouteParse {
  return { ok: false, error: { message } }
}

// Build the prompt, run the agent, parse the reply. The caller (server function)
// supplies the transcript, the board tickets, the skill body, and the real
// spawn; on success it fans the briefs out to stage 2's per-ticket refine.
export async function runRoute(
  input: RouteInput & { readonly skillBody: string },
  run: RunClaude,
): Promise<RouteParse> {
  const args = routeClaudeArgs(input.skillBody)
  const prompt = buildRoutePrompt(input)
  return parseRouteResult(await run(args, prompt), canonicalKeyMap(input.tickets))
}
